services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: vsDB